feat: 로그인 기능 추가 / docs: 회원가입 페이지 루트명 변경
fastcampus-final/go-together-fe pull request #17
Opened 2023-03-15 10:34 UTC by dreamchach

# 📍 이슈 번호

#12 

# 📚 작업 내용
- 회원가입페이지 폴더명 변경
- 로그인 token값 쿠키에 저장
- 로그인 성공 시 뒤로가기 기능
- 로그인 된 상태에서 들어오지 못하게 함

# 💬 특이 사항

2023-03-15 11:04 UTC, autumnly1007 requested changes

2023-03-15 11:04 UTC, autumnly1007 commented on pages/signup/success.tsx
> +      <Link href="/survey">
페이지 경로 상수 파일 routes.ts 안의 ROUTES 객체를 import 해서 사용해주시면 감사하겠습니다.

2023-03-15 11:04 UTC, autumnly1007 commented on pages/signup/index.tsx
> +    alert('로그인된 계정입니다. 로그아웃 후 이용해주세요.');
메시지는 상수 파일 messages.ts 안에서 작성 후 import 하여 사용 부탁드립니다.

2023-03-15 11:31 UTC, autumnly1007 commented
PR 제목에 prefix 도 안붙이셔도 됩니당!

2023-03-15 11:32 UTC, plou102 commented
설치해야 할것들 정리 한번 부탁드려욥~!

2023-03-16 01:56 UTC, autumnly1007 commented on pages/login/index.tsx
> +      alert('로그인된 계정입니다. 로그아웃 후 이용해주세요.');
이부분도 상수 값 사용 부탁드립니다

2023-03-16 04:51 UTC, merged

2023-03-16 04:52 UTC, autumnly1007 commented
수고하셨습니다 !! 👍